### DISCUSSION TITLE
Seatunnel add nodes to cluster...for parallel job execution

### DISCUSSION THREAD

**Discussion by shrikhaparul** [apache/seatunnel#6340] [General]
how can we achieve Seatunnel add nodes to cluster...for parallel job execution

**Comment by cqutwangyu** [comment]
How to deploy multi-node cluster?

**Reply by cqutwangyu** [reply]
hazelcast.yaml
```
hazelcast:
  cluster-name: seatunnel
  network:
    rest-api:
      enabled: true
      endpoint-groups:
        CLUSTER_WRITE:
          enabled: true
        DATA:
          enabled: true
    join:
      tcp-ip:
        enabled: true
        member-list:
          - 10.11.50.36
          - 10.11.50.37
    port:
      auto-increment: false
      port: 5801
  properties:
    hazelcast.invocation.max.retry.count: 20
    hazelcast.tcp.join.port.try.count: 30
    hazelcast.logging.type: log4j2
    hazelcast.operation.generic.thread.count: 50
```

hazelcast-client.yaml
```
hazelcast-client:
  cluster-name: seatunnel
  properties:
    hazelcast.logging.type: log4j2
  connection-strategy:
    connection-retry:
      cluster-connect-timeout-millis: 3000
  network:
    cluster-members:
      - 10.11.50.36:5801
      - 10.11.50.37:5801
```
﻿
