### DISCUSSION TITLE
The Zeta server cannot find other members via Kubernetes since after bump a version from 2.3.5 to 2.3.7

### DISCUSSION THREAD

**Discussion by loustler** [apache/seatunnel#7750] [Q&A] [answered]
Hi folks

A Zeta server couldn't find other members via Kubernetes API since after bump a version from 2.3.5 to 2.3.7
I've glanced over a PR #6947  I think related with this issue, but I couldn't find any problems.
Below a configuration is still valid since after 2.3.6?
It's working with a same configuration in 2.3.5.

Starting a cluster like this
```
/opt/seatunnel/bin/seatunnel-cluster.sh
```

hazelcast.yaml
```yaml
hazelcast:
      cluster-name: seatunnel
      network:
        rest-api:
          enabled: true
          endpoint-groups:
            CLUSTER_WRITE:
              enabled: true
            DATA:
              enabled: true
        join:
          multicast:
            enabled: false
          kubernetes:
            enabled: true
            service-port: 5801
            namespace: MY_NAMESPACE
            service-name: seatunnel
        port:
          auto-increment: false
          port: 5801
      properties:
        hazelcast.logging.type: log4j2
        hazelcast.invocation.max.retry.count: 100
        hazelcast.invocation.retry.pause.millis: 1000
        hazelcast.tcp.join.port.try.count: 30
        hazelcast.slow.operation.detector.stacktrace.logging.enabled: true
        hazelcast.operation.generic.thread.count: 50
        hazelcast.client.invocation.timeout.seconds: 3600
```

Thanks for all your supports
