### ISSUE TITLE
seatunnel 2.3.8 中设置imap持久化配置后未生效

### ISSUE THREAD

**Issue by bitifi2019** [apache/seatunnel#9283]
运行环境信息：
OS: centos 7.9
java version: 1.8.0_441
seatunnel: 2.3.8

配置信息:
seatunnel.yaml
```
seatunnel:
  engine:
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 300000
      timeout: 30000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          namespace: /data/seatunnel/checkpoint_snapshot
          storage.type: hdfs
          fs.defaultFS: file:///data/
    classloader-cache-mode: true
    telemetry:
      metric:
        enabled: true
map:
 engine*:
   map-store:
     enable: true
     initial-mode: EAGER
     factory-class-name: org.apache.seatunnel.engine.server.persistence.FileMapStoreFactory
     properties:
       type: hdfs
       namespace: /data/seatunnel/imap
       clusterName: seatunnel-test
       storage.type: hdfs
       fs.defaultFS: file:///
```
运行的job:
Job ID              Job Name       Job Status  Submit Time              Finished Time            
------------------  -------------  ----------  -----------------------  -----------------------  
972400938104913922  SeaTunnel_Job  RUNNING     2025-05-07 15:34:10.281  

/data/seatunnel/目录信息：
tree -l seatunnel/
seatunnel/
├── checkpoint_snapshot
│   └── 972400938104913922
│       ├── 1746603325288-981-1-37.ser
│       ├── 1746603327288-460-1-38.ser
│       ├── 1746603329290-580-1-39.ser
│       └── 1746603331288-731-1-40.ser
└── imap
