### ISSUE TITLE
hdfs imap空间越占越大

### ISSUE THREAD

**Issue by foxbei** [apache/seatunnel#9472]
seatunnel 2.3.11 分离模式集群，mysql cdc 任务运行后，保存在hdfs中的imap下engine_runningJobMetrics中内容持续增加，并不能定期清理。请问，这里的文件直接手动删除会不会对同步任务的保存、恢复有影响

![Image](https://github.com/user-attachments/assets/fc6e78a2-e68b-4df1-beff-dc584b1b9bae)

**Comment by foxbei** [comment]
相关的配置：
```seatunnel:
  engine:
    classloader-cache-mode: true
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
```

**Comment by prclin** [comment]
map-store持久化配置能发出来一下，类似：
```yaml
map:
    engine*:
      map-store:
        enabled: true
        initial-mode: EAGER
        factory-class-name: org.apache.seatunnel.engine.server.persistence.FileMapStoreFactory
        properties:
          type: hdfs
          clusterName: seatunnel-cluster
```
