### ISSUE TITLE
[Bug] [plugins] image: apache/seatunnel install-plugin.sh failed within docker container caused by absence of /opt/seatunnel/mvnw: not found

### ISSUE THREAD

**Issue by suntectec** [apache/seatunnel#9522]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Specify config/plugin_config and install-plugin.sh, failed within docker container caused by absence of /opt/seatunnel/mvnw: not found

### SeaTunnel Version

2.3.11

### docker-compose.yml

```
services:
  master:
    container_name: seatunnel-master
    image: apache/seatunnel
    environment:
      - ST_DOCKER_MEMBER_LIST=172.16.0.2,172.16.0.3,172.16.0.4
    entrypoint: >
      /bin/sh -c "
      /opt/seatunnel/bin/seatunnel-cluster.sh -r master
      "
    ports:
      - "15801:5801"
      - "18080:8080"
    networks:
      seatunnel_network:
        ipv4_address: 172.16.0.2
    volumes:
      - ./seatunnel/config:/config
      - ./seatunnel/plugin_config:/opt/seatunnel/config/plugin_config
```

### Plugin Config

```
--connectors-v2--
connector-cdc-mysql
connector-cdc-sqlserver
connector-cdc-oracle
connector-file-hadoop
connector-file-local
connector-file-s3
connector-hive
connector-iceberg
connector-jdbc
connector-kafka
connector-paimon
```

### Running Command

```shell
sh bin/install-plugin.sh
```

### Error Exception

```log
bin/install-plugin.sh: 48: /opt/seatunnel/mvnw: not found
```

### Java or Scala Version

11

### Screenshots

![Image](https://github.com/user-attachments/assets/48dfb23d-ff5b-4a64-bf03-e2ead0059656)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
